version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PHP_MEM_LIMIT=256
      - SKIP_CHOWN=true
    env_file:
      - .env
    ports:
      - '80:80'
    container_name: app_project_diego

  db-psql:
    image: postgres:9.6
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=senhaSuPErSeCREt@
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db-project-diego
      - TZ='America/Sao_Paulo'
    volumes:
      - ./db:/var/lib/postgresql/data/